version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

references:
  default_ruby_version: &default_ruby_version 2.6.3-stretch-node
  ruby_envs: &ruby_envs
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
executors:
  default:
    parameters:
      ruby_tag:
        description: "The `circleci/ruby` Docker image version tag."
        type: string
        default: *default_ruby_version
    docker:
      - image: circleci/ruby:<< parameters.ruby_tag >>
        <<: *ruby_envs
  ruby_sinatra:
    parameters:
      ruby_tag:
        description: "The `circleci/postgres` Docker image version tag."
        type: string
        default: *default_ruby_version

jobs:
  build:
    executor: default
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/load-cache:
          key: rails-demo-bundle
      - ruby/bundle-install
      - ruby/save-cache:
          key: rails-demo-bundle
  test:
    parallelism: 3
    executor: ruby_sinatra
    steps:
      - checkout
      - ruby/load-cache:
          key: rails-demo-bundle
      - ruby/bundle-install
      - ruby/test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
