version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
orbs:
  ruby: circleci/ruby@1.0

executors:
  my-executor:
    docker:
      - image: cimg/ruby:2.7-node
        auth:
          username: duydyy
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: /tmp

jobs:
  build: # our first job, named "build"
    executor: my-executor
    working_directory: ~/oivan
    steps:
      - checkout # pull down our git code.
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps # use the ruby orb to install dependencies
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

  test:  # our next job, called "test"
    # we run "parallel job containers" to enable speeding up our tests;
    # this splits our tests across multiple containers.
    parallelism: 3
    # here we set TWO docker images.
    executor: my-executor
    working_directory: ~/oivan

    # environment variables specific to Ruby/Rails, applied to the primary container.
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    # A series of steps to run, some are similar to those in "build".
    steps:
      - checkout
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps
      - run: RACK_ENV=test bundle exec rake storage:create
      - run: bundle exec rspec spec

  deploy-dev:
    executor: my-executor
    working_directory: ~/oivan
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:6e:c6:74:f5:3a:1a:e4:4c:87:2e:96:24:21:a4:cc"
      - run: ssh-keyscan 45.77.244.152 >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt install rsync
      - checkout # pull down our git code.
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps # use the ruby orb to install dependencies
      - run: bundle exec rake storage:create
      - run:
          name: deploy
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/oivan/ root@45.77.244.152:/srv/oivan/dev
      - run:
          name: restart services
          command: ssh root@45.77.244.152 'sudo systemctl restart oivan_dev.service'

  deploy-prd:
    executor: my-executor
    working_directory: ~/oivan
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:6e:c6:74:f5:3a:1a:e4:4c:87:2e:96:24:21:a4:cc"
      - run: ssh-keyscan 45.77.244.152 >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt install rsync
      - checkout # pull down our git code.
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps # use the ruby orb to install dependencies
      - run: RACK_ENV=production bundle exec rake storage:create
      - run: RACK_ENV=production bundle exec rake assets:compile
      - run:
          name: deploy
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/oivan/ root@45.77.244.152:/srv/oivan/prd
      - run:
          name: restart services
          command: ssh root@45.77.244.152 'sudo systemctl restart oivan_prd.service'
  
  # deploy:
  #   executor: my-executor
  #   working_directory: ~/oivan
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "a7:6e:c6:74:f5:3a:1a:e4:4c:87:2e:96:24:21:a4:cc"
  #     - run: ssh-keyscan 45.77.244.152 >> ~/.ssh/known_hosts
  #     - run: sudo apt update
  #     - run: sudo apt install rsync
  #     - checkout # pull down our git code.
  #     - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
  #         key: deps1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  #     - ruby/install-deps # use the ruby orb to install dependencies
  #     - run:
  #         name: deploy
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" = "main" ]; then
  #             rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/oivan/ root@45.77.244.152:/srv/oivan/prd
  #           elif [ "${CIRCLE_BRANCH}" = "develop" ]; then
  #             rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/oivan/ root@45.77.244.152:/srv/oivan/dev
  #           else
  #             echo "Not deploy branches, dry run only"
  #           fi
  #     - run:
  #         name: restart services
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" = "main" ]; then
  #             ssh root@45.77.244.152 'sudo systemctl restart oivan_prd.service'
  #           elif [ "${CIRCLE_BRANCH}" = "develop" ]; then
  #             ssh root@45.77.244.152 'sudo systemctl restart oivan_dev.service'
  #           else
  #             echo "Not deploy branches, dry run only"
  #           fi

# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build         # Run build first.
      - test:         # Then run test,
          requires:   # Test requires that build passes for it to run.
            - build   # Finally, run the build job.
      - deploy:
          requires:
            - test
          jobs:
            - deploy-dev:
                filters:
                  branches:
                    only: develop
            - deploy-prd:
                filters:
                  branches:
                    only: main
